var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,d){a.raw=d;return a};var $jscomp$templatelit$m48754569$0=$jscomp.createTemplateTagFirstArg([" "]),$jscomp$templatelit$m48754569$1=$jscomp.createTemplateTagFirstArg([" "]);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(a==Array.prototype||a==Object.prototype)return a;a[d]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var b=a[d];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,d){var b=$jscomp.propertyToPolyfillSymbol[d];if(null==b)return a[d];b=a[b];return void 0!==b?b:a[d]};$jscomp.polyfill=function(a,d,b,g){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,b,g):$jscomp.polyfillUnisolated(a,d,b,g))};
$jscomp.polyfillUnisolated=function(a,d,b,g){b=$jscomp.global;a=a.split(".");for(g=0;g<a.length-1;g++){var e=a[g];if(!(e in b))return;b=b[e]}a=a[a.length-1];g=b[a];d=d(g);d!=g&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,b,g){var e=a.split(".");a=1===e.length;g=e[0];g=!a&&g in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<e.length-1;l++){var k=e[l];if(!(k in g))return;g=g[k]}e=e[e.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?g[e]:null;d=d(b);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:d}):d!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+b+"$"+e),$jscomp.defineProperty(g,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:d})))};$jscomp.polyfill("Object.is",function(a){return a?a:function(d,b){return d===b?0!==d||1/d===1/b:d!==d&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(d,b){var g=this;g instanceof String&&(g=String(g));var e=g.length;b=b||0;for(0>b&&(b=Math.max(b+e,0));b<e;b++){var l=g[b];if(l===d||Object.is(l,d))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,d,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(d,b){return-1!==$jscomp.checkStringArgs(this,d,"includes").indexOf(d,b||0)}},"es6","es3");
function spr(a,d,b){d=void 0===d?document.body.appendChild(document.createElement("div")):d;b=void 0===b?"https://cdn.jsdelivr.net/gh/jaketrock/newSprint/css/ns_prod.css":b;"\u00a9 Jacob Trock";if(!window.nsht){var g=document.head.appendChild(document.createElement("link"));g.rel="stylesheet";g.href=b}var e=localStorage.getItem("nsp+")||localStorage.setItem("nsp+","200")||200,l=0,k,n,h,q,p,w,r=!1,A=function(c){return m.slice(void 0===c?0:c).reduce(function(f,x){return f+1E3/(e/60)*(.5*(x.length/5-
1)+1)},0)},m="string"==typeof a?a.split($jscomp$templatelit$m48754569$0).filter(function(c){return c}).map(function(c){return c.includes("](")?"<a href="+c.split(/[()]/)[1]+">"+c.split(/\[(.*?)\]/)[1]+"</a>":c}):[].concat.apply([],Array.prototype.slice.call(a).map(function(c){return c.href?c.innerHTML.link(c.href):(c.innerHTML||c.value).split($jscomp$templatelit$m48754569$1)})).filter(function(c){return c}),y=A(),t=function(c){0<=+e+c&&(localStorage.setItem("nsp+",e=+e+c),y=A());p.value=e},B=function(c){var f=
(c%6E4/1E3).toFixed(0);return~~(c/6E4)+":"+(10>f?"0":"")+f},z=function(c){if(r&&m.length){var f=m[c++];if(f){h.value=c;3>f.length&&(f+=" "+m[c++]);k.innerHTML=f;w.innerHTML=B(y-A(c))+"/"+B(y);var x=setTimeout(function(){x===l&&z(c)},1E3/(e/60)*(.5*(f.length/5-1)+1));l=x}else clearTimeout(l),k.innerHTML="&#8635;&#xFE0E;",k.addEventListener("click",function(){return z(0)})}},u=function(){r=!r;q.innerHTML=(r?"&#9208;":"&#9654;")+"&#xFE0E;";h.disabled=!1;r?z(h.value):localStorage.setItem("nstcd",h.value)},
C=function(){window.nsht=d.innerHTML=""},v=function(c){c=~~Number(h.value)+c;u();switch(c){case 0>c:h.value=0;break;case c>m.length:h.value=m.length;break;default:h.value=c}u()};document.body.onwheel=function(c){return v(c.deltaY)};document.body.onkeydown=function(c){switch(c.key){case " ":u();break;case "Escape":C();break;case "ArrowRight":v(m.length/e);break;case "ArrowLeft":v(-m.length/e);break;case "ArrowUp":t(10);break;case "ArrowDown":t(-10)}};(function(){C();n=d.appendChild(document.createElement("div"));
window.nsht=n;k=n.appendChild(document.createElement("div"));n.className="nsp_out";h=n.appendChild(document.createElement("input"));h.type="range";h.value=h.min=0;h.step=1;h.max=m.length;h.className="nsp_sli";h.disabled=!0;h.addEventListener("change",function(){z(h.value);k.innerHTML=m[h.value]});var c=n.appendChild(document.createElement("div"));c.className="nsp_wdu";var f=c.appendChild(document.createElement("button"));f.className="nsp_btn";f.innerHTML="-";f.addEventListener("click",function(){return t(-10)});
p=c.appendChild(document.createElement("input"));p.type="text";p.size="2";p.className="nsp_wad";p.value=e;p.addEventListener("blur",function(){return t(p.value-e)});f=c.appendChild(document.createElement("button"));f.className="nsp_btn";f.innerHTML="+";f.addEventListener("click",function(){return t(10)});c=n.appendChild(document.createElement("div"));c.className="nsp_mcl";q=c.appendChild(document.createElement("button"));q.className="nsp_btn";q.innerHTML="&#9654;&#xFE0E;";q.addEventListener("click",
function(){return u()});f=c.appendChild(document.createElement("button"));f.className="nsp_btn nsp_bl";f.innerHTML="&#9194;&#xFE0E;";f.addEventListener("click",function(){return v(-e/4)});w=n.appendChild(document.createElement("div"));w.className="nsp_tmr";w.innerHTML="0:00/"+B(y);f=c.appendChild(document.createElement("button"));f.className="nsp_btn nsp_bl";f.innerHTML="&#9193;&#xFE0E;";f.addEventListener("click",function(){return v(e/4)});f=c.appendChild(document.createElement("button"));f.className=
"nsp_btn nsp_bl";f.innerHTML="&times;&#xFE0E;";f.addEventListener("click",function(){return C()});k.className="nsp_inr";k.innerHTML="&#9654;&#xFE0E;";k.addEventListener("click",function(){return u()})})();h.value=Number(localStorage.getItem("nstcd"))||localStorage.setItem("nstcd",0)||0}window.nsprint=spr;