function B(b){return b.raw=b}var F=B([" "]),H=B([" "]),I="function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){if(b==Array.prototype||b==Object.prototype)return b;b[d]=c.value;return b};function J(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<b.length;++d){var c=b[d];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var K=J(this);
function L(b,d){if(d)a:{var c=K;b=b.split(".");for(var f=0;f<b.length-1;f++){var n=b[f];if(!(n in c))break a;c=c[n]}b=b[b.length-1];f=c[b];d=d(f);d!=f&&null!=d&&I(c,b,{configurable:!0,writable:!0,value:d})}}L("Object.is",function(b){return b?b:function(d,c){return d===c?0!==d||1/d===1/c:d!==d&&c!==c}});
L("Array.prototype.includes",function(b){return b?b:function(d,c){var f=this;f instanceof String&&(f=String(f));var n=f.length;c=c||0;for(0>c&&(c=Math.max(c+n,0));c<n;c++){var p=f[c];if(p===d||Object.is(p,d))return!0}return!1}});
L("String.prototype.includes",function(b){return b?b:function(d,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(d,c||0)}});
window.nsprint=function(b,d,c){function f(a){a=~~Number(k.value)+a;p();switch(a){case 0>a:k.value=0;break;case a>m.length:k.value=m.length;break;default:k.value=a}p()}function n(){d.innerHTML="";window.g=!1}function p(){u=!u;v.innerHTML=(u?"&#9208;":"&#9654;")+"&#xFE0E;";k.disabled=!1;u&&x(k.value)}function x(a){if(u&&m.length){var e=m[a++];if(e){k.value=a;3>e.length&&(e+=" "+m[a++]);q.innerHTML=e;y.innerHTML=C(z-D(a))+"/"+C(z);var A=setTimeout(function(){A===E&&x(a)},1E3/(l/60)*(.5*(e.length/5-1)+
1));E=A}else clearTimeout(E),q.innerHTML="&#8635;&#xFE0E;",q.addEventListener("click",function(){return x(0)})}}function C(a){var e=(a%6E4/1E3).toFixed(0);return~~(a/6E4)+":"+(10>e?"0":"")+e}function w(a){0<=+l+a&&(localStorage.setItem("nsp+",l=+l+a),z=D());r.value=l}function D(a){return m.slice(void 0===a?0:a).reduce(function(e,A){return e+1E3/(l/60)*(.5*(A.length/5-1)+1)},0)}d=void 0===d?document.body.appendChild(document.createElement("div")):d;c=void 0===c?"https://cdn.jsdelivr.net/gh/jaketrock/newSprint/css/ns_prod.css":
c;"\u00a9 Jacob Trock";if(!0!==nswr){var G=document.head.appendChild(document.createElement("link"));G.rel="stylesheet";G.href=c}window.h=!0;var l=localStorage.getItem("nsp+")||200,E=0,q,t,k,v,r,y,u=!1,m="string"==typeof b?b.split(F).filter(function(a){return a}).map(function(a){return a.includes("](")?"<a href="+a.split(/[()]/)[1]+">"+a.split(/\[(.*?)\]/)[1]+"</a>":a}):[].concat.apply([],Array.prototype.slice.call(b).map(function(a){return a.href?a.innerHTML.link(a.href):(a.innerHTML||a.value).split(H)})).filter(function(a){return a}),
z=D();document.body.onkeydown=function(a){switch(a.key){case " ":p();break;case "Escape":n();break;case "ArrowRight":f(m.length/l);break;case "ArrowLeft":f(-m.length/l);break;case "ArrowUp":w(10);break;case "ArrowDown":w(-10)}};document.body.addEventListener("wheel",function(a){return f(a.deltaY)});(function(){n();window.g=!0;t=d.appendChild(document.createElement("div"));q=t.appendChild(document.createElement("div"));t.className="nsp_out";k=t.appendChild(document.createElement("input"));k.type="range";
k.value=k.min=0;k.step=1;k.max=m.length;k.className="nsp_sli";k.disabled=!0;k.addEventListener("change",function(){x(k.value);q.innerHTML=m[k.value]});var a=t.appendChild(document.createElement("div"));a.className="nsp_wdu";var e=a.appendChild(document.createElement("button"));e.className="nsp_btn";e.innerHTML="-";e.addEventListener("click",function(){return w(-10)});r=a.appendChild(document.createElement("input"));r.type="text";r.size="2";r.className="nsp_wad";r.value=l;r.addEventListener("blur",
function(){return w(r.value-l)});e=a.appendChild(document.createElement("button"));e.className="nsp_btn";e.innerHTML="+";e.addEventListener("click",function(){return w(10)});a=t.appendChild(document.createElement("div"));a.className="nsp_mcl";v=a.appendChild(document.createElement("button"));v.className="nsp_btn";v.innerHTML="&#9654;&#xFE0E;";v.addEventListener("click",function(){return p()});e=a.appendChild(document.createElement("button"));e.className="nsp_btn nsp_bl";e.innerHTML="&#9194;&#xFE0E;";
e.addEventListener("click",function(){return f(-l/4)});y=t.appendChild(document.createElement("div"));y.className="nsp_tmr";y.innerHTML="0:00/"+C(z);e=a.appendChild(document.createElement("button"));e.className="nsp_btn nsp_bl";e.innerHTML="&#9193;&#xFE0E;";e.addEventListener("click",function(){return f(l/4)});e=a.appendChild(document.createElement("button"));e.className="nsp_btn nsp_bl";e.innerHTML="&times;&#xFE0E;";e.addEventListener("click",function(){return n()});q.className="nsp_inr";q.innerHTML=
"&#9654;&#xFE0E;";q.addEventListener("click",function(){return p()})})()};
