function A(c){return c.raw=c}var C="function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,e){if(c==Array.prototype||c==Object.prototype)return c;c[d]=e.value;return c};function D(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<c.length;++d){var e=c[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var E=D(this);
function F(c,d){if(d)a:{var e=E;c=c.split(".");for(var g=0;g<c.length-1;g++){var h=c[g];if(!(h in e))break a;e=e[h]}c=c[c.length-1];g=e[c];d=d(g);d!=g&&null!=d&&C(e,c,{configurable:!0,writable:!0,value:d})}}
F("Array.from",function(c){return c?c:function(d,e,g){e=null!=e?e:function(u){return u};var h=[],l="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];if("function"==typeof l){d=l.call(d);for(var m=0;!(l=d.next()).done;)h.push(e.call(g,l.value,m++))}else for(l=d.length,m=0;m<l;m++)h.push(e.call(g,d[m],m));return h}});var G=A([" "]),H=A([" "]);
window.nsprint=function(c,d,e){function g(a){a=~~Number(f.value)+a;h();switch(a){case 0>a:f.value=0;break;case a>p.length:f.value=p.length;break;default:f.value=a}h()}function h(){v=!v;f.disabled=!1;v&&l(f.value)}function l(a){if(v&&p.length){var b=p[a++];if(b){f.value=a;3>b.length&&(b+=" "+p[a++]);q.innerHTML=b;w.innerHTML=m(x-y(a))+"/"+m(x);var r=setTimeout(function(){r===z&&l(a)},1E3/(k/60)*(.5*(b.length/5-1)+1));z=r}else clearTimeout(z),q.innerHTML="&#8635;&#xFE0E;",q.addEventListener("click",
function(){return l(0)})}}function m(a){var b=(a%6E4/1E3).toFixed(0);return~~(a/6E4)+":"+(10>b?"0":"")+b}function u(a){0<=+k+a&&(localStorage.setItem("4f:04:82",k=+k+a),x=y());t.value=k}function y(a){return p.slice(void 0===a?0:a).reduce(function(b,r){return b+1E3/(k/60)*(.5*(r.length/5-1)+1)},0)}d=void 0===d?Array.from(document.getElementsByTagName("body"))[0].appendChild(document.createElement("div")):d;e=void 0===e?"https://cdn.jsdelivr.net/gh/jaketrock/newSprint/css/ns_prod.css":e;var B=Array.prototype.slice.call(document.getElementsByTagName("head"))[0].appendChild(document.createElement("link"));
B.rel="stylesheet";B.href=e;var k=localStorage.getItem("4f:04:82")||200,z=0,q,n,f,t,w,v=!1,p="string"==typeof c?c.split(G).filter(function(a){return a}):["--3--","--2--","--1--"].concat([].concat.apply([],Array.prototype.slice.call(c).map(function(a){return a.href?a.innerHTML.link(a.href):(a.innerHTML||a.value).split(H)})).filter(function(a){return a})),x=y();(function(){d.innerHTML="";n=d.appendChild(document.createElement("div"));q=n.appendChild(document.createElement("div"));n.className="nsp_out";
f=n.appendChild(document.createElement("input"));f.type="range";f.value=f.min=0;f.step=1;f.max=p.length;f.className="nsp_sli";f.disabled=!0;f.addEventListener("change",function(){l(f.value);q.innerHTML=p[f.value]});var a=n.appendChild(document.createElement("div"));a.className="nsp_wdu";var b=a.appendChild(document.createElement("button"));b.className="nsp_wb";b.innerHTML="-";b.addEventListener("click",function(){return u(-10)});t=a.appendChild(document.createElement("input"));t.type="text";t.size=
"2";t.className="nsp_wad";t.value=k;t.addEventListener("blur",function(){return u(t.value-k)});b=a.appendChild(document.createElement("button"));b.className="nsp_wb";b.innerHTML="+";b.addEventListener("click",function(){return u(10)});a=n.appendChild(document.createElement("div"));a.className="nsp_mcl";b=a.appendChild(document.createElement("button"));b.className="nsp_pb";b.innerHTML="&#9199;&#xFE0E;";b.addEventListener("click",function(){return h()});b=a.appendChild(document.createElement("button"));
b.className="nsp_btn";b.innerHTML="&#9194;&#xFE0E;";b.addEventListener("click",function(){return g(-k/4)});w=n.appendChild(document.createElement("div"));w.className="nsp_tmr";w.innerHTML="0:00/"+m(x);b=a.appendChild(document.createElement("button"));b.className="nsp_btn";b.innerHTML="&#9193;&#xFE0E;";b.addEventListener("click",function(){return g(k/4)});b=a.appendChild(document.createElement("button"));b.className="nsp_btn";b.innerHTML="&times;&#xFE0E;";b.addEventListener("click",function(){d.innerHTML=
""});q.className="nsp_inr";q.innerHTML="Press play";q.addEventListener("click",function(){return h()});n.onkeydown=function(r){switch(r.keyCode){case 32:h();break;case 27:d.innerHTML="";break;case 39:g(k/4);break;case 37:g(-k/4);break;case 38:u(10);break;case 40:u(-10)}};n.addEventListener("wheel",function(r){g(r.wheelDelta/12)})})()};
