function z(b){return b.raw=b}var A="function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){if(b==Array.prototype||b==Object.prototype)return b;b[c]=d.value;return b};function B(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");}var C=B(this);
function D(b,c){if(c)a:{var d=C;b=b.split(".");for(var g=0;g<b.length-1;g++){var l=b[g];if(!(l in d))break a;d=d[l]}b=b[b.length-1];g=d[b];c=c(g);c!=g&&null!=c&&A(d,b,{configurable:!0,writable:!0,value:c})}}
D("Array.from",function(b){return b?b:function(c,d,g){d=null!=d?d:function(u){return u};var l=[],n="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];if("function"==typeof n){c=n.call(c);for(var h=0;!(n=c.next()).done;)l.push(d.call(g,n.value,h++))}else for(n=c.length,h=0;h<n;h++)l.push(d.call(g,c[h],h));return l}});var E=z([" "]);
window.nsprint=function(b,c){function d(a){g();l(Number(f.value)+a);g()}function g(){v=!v;f.disabled=!1;v&&l(f.value)}function l(a){if(v&&r.length){var e=r[a++];if(e){f.value=a;3>e.length&&(e+=" "+r[a++]);t.innerHTML=e;w.innerHTML=n(x-u(a))+"/"+n(x);var p=setTimeout(function(){p===y&&l(a)},1E3/(k/60)*(.5*(e.length/5-1)+1));y=p}else clearTimeout(y),t.innerHTML='<a onclick="nextWord(0)">&#8635;&#xFE0E;</a>'}}function n(a){var e=(a%6E4/1E3).toFixed(0);return~~(a/6E4)+":"+(10>e?"0":"")+e}function h(a){0<=
+k+a&&(localStorage.setItem("4f:04:82",k=+k+a),x=u());q.value=k}function u(a){return r.slice(void 0===a?0:a).reduce(function(e,p){return e+1E3/(k/60)*(.5*(p.length/5-1)+1)},0)}c=void 0===c?Array.from(document.getElementsByTagName("body"))[0].appendChild(document.createElement("div")):c;var k=localStorage.getItem("4f:04:82")||200,y=0,t,m,f,q,w,v=!1,r=["--3--","--2--","--1--"].concat([].concat.apply([],Array.prototype.slice.call(b).map(function(a){return a.href?a.innerHTML.link(a.href):(a.innerHTML||
a.value).split(E)})).filter(function(a){return a})),x=u();(function(){c.innerHTML="";m=c.appendChild(document.createElement("div"));t=m.appendChild(document.createElement("div"));m.style.cssText="position:sticky;left:0px;height:10%;width:100%;background:#f5f5f5;font-size:70px;font-size: 5em;text-align:center;line-height:100px;flex-direction:row;justify-content:center;align-items:center;display:flex;border-top:3px solid;border-bottom:3px solid;";var a=m.appendChild(document.createElement("div"));a.style.cssText=
"width:3px;background:black;height:7px;position:absolute;top:0px;left:50%;";a=m.appendChild(document.createElement("div"));a.style.cssText="width:3px;background:black;height:7px;position:absolute;bottom:0px;left:50%;";f=m.appendChild(document.createElement("input"));f.type="range";f.value=f.min=0;f.step=1;f.max=r.length;f.style.cssText="width:100%;height:4px;position:absolute;bottom:0px;";f.disabled=!0;f.addEventListener("change",function(){l(f.value);t.innerHTML=r[f.value]});var e=m.appendChild(document.createElement("div"));
e.style.cssText="position:absolute;left:10px;flex-direction:row;display:flex;align-items:center;top:5px;";a=e.appendChild(document.createElement("button"));a.style.cssText="background:#eeeeee;color:black;border:none;font-size:10px;font-size: 0.25em;";a.innerHTML="-";a.addEventListener("click",function(){return h(-10)});q=e.appendChild(document.createElement("input"));q.type="text";q.size="2";q.style.cssText="font-size:10px;font-size: 0.25em;line-height:10px;height:50%;margin:10px;";q.value=k;q.addEventListener("blur",
function(){return h(q.value-k)});a=e.appendChild(document.createElement("button"));a.style.cssText="background:#eeeeee;color:black;border:none;font-size:10px;font-size: 0.25em;";a.innerHTML="+";a.addEventListener("click",function(){return h(10)});e=m.appendChild(document.createElement("div"));e.style.cssText="position:absolute;right:10px;flex-direction:row;display:flex;align-items:center;top:5px;";a=e.appendChild(document.createElement("button"));a.style.cssText="background:red;color:black;border:none;font-size:10px;font-size: 0.25em;";
a.innerHTML="&#9194;&#xFE0E;";a.addEventListener("click",function(){return d(-k/4)});a=e.appendChild(document.createElement("button"));a.style.cssText="background:red;color:black;border:none;border-left: 1px solid black;font-size:10px;font-size: 0.25em;";a.innerHTML="&#9199;&#xFE0E;";a.addEventListener("click",function(){return g()});a=e.appendChild(document.createElement("button"));a.style.cssText="background:red;color:black;border:none;border-left: 1px solid black;font-size:10px;font-size: 0.25em;";
a.innerHTML="&#9193;&#xFE0E;";a.addEventListener("click",function(){return d(k/4)});a=e.appendChild(document.createElement("button"));a.style.cssText="background:red;color:black;border:none;border-left:1px solid black;font-size:10px;font-size: 0.25em;";a.innerHTML="&times;&#xFE0E;";a.addEventListener("click",function(){c.innerHTML=""});w=m.appendChild(document.createElement("div"));w.style.cssText="position:absolute;right:10px;flex-direction:row;display:flex;align-items:center;bottom:5px;font-size:10px;font-size: 0.25em;height:15px;";
w.innerHTML="0:00/"+n(x);t.style.cssText="display:inline-block;transform:translate(8%);";t.innerHTML="Press play";m.onkeydown=function(p){switch(p.keyCode){case 32:g();break;case 27:c.innerHTML="";break;case 39:d(k/4);break;case 37:d(-k/4);break;case 38:h(10);break;case 40:h(-10)}};m.addEventListener("wheel",function(p){d(p.wheelDelta/12)})})()};
