function z(c){return c.raw=c}var A="function"==typeof Object.defineProperties?Object.defineProperty:function(c,d,e){if(c==Array.prototype||c==Object.prototype)return c;c[d]=e.value;return c};function B(c){c=["object"==typeof globalThis&&globalThis,c,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<c.length;++d){var e=c[d];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");}var C=B(this);
function D(c,d){if(d)a:{var e=C;c=c.split(".");for(var g=0;g<c.length-1;g++){var h=c[g];if(!(h in e))break a;e=e[h]}c=c[c.length-1];g=e[c];d=d(g);d!=g&&null!=d&&A(e,c,{configurable:!0,writable:!0,value:d})}}
D("Array.from",function(c){return c?c:function(d,e,g){e=null!=e?e:function(u){return u};var h=[],m="undefined"!=typeof Symbol&&Symbol.iterator&&d[Symbol.iterator];if("function"==typeof m){d=m.call(d);for(var k=0;!(m=d.next()).done;)h.push(e.call(g,m.value,k++))}else for(m=d.length,k=0;k<m;k++)h.push(e.call(g,d[k],k));return h}});var E=z([" "]);
window.nsprint=function(c,d){function e(a){g();console.log(Number(f.value)+a);h(Number(f.value)+a);g()}function g(){v=!v;f.disabled=!1;v&&h(f.value)}function h(a){if(v&&t.length){var b=t[a++];if(b){f.value=a;3>b.length&&(b+=" "+t[a++]);p.innerHTML=b;w.innerHTML=m(x-u(a))+"/"+m(x);var q=setTimeout(function(){q===y&&h(a)},1E3/(l/60)*(.5*(b.length/5-1)+1));y=q}else clearTimeout(y),p.innerHTML="&#8635;&#xFE0E;",p.addEventListener("click",function(){return h(0)})}}function m(a){var b=(a%6E4/1E3).toFixed(0);
return~~(a/6E4)+":"+(10>b?"0":"")+b}function k(a){0<=+l+a&&(localStorage.setItem("4f:04:82",l=+l+a),x=u());r.value=l}function u(a){return t.slice(void 0===a?0:a).reduce(function(b,q){return b+1E3/(l/60)*(.5*(q.length/5-1)+1)},0)}d=void 0===d?Array.from(document.getElementsByTagName("body"))[0].appendChild(document.createElement("div")):d;var l=localStorage.getItem("4f:04:82")||200,y=0,p,n,f,r,w,v=!1,t=["--3--","--2--","--1--"].concat([].concat.apply([],Array.prototype.slice.call(c).map(function(a){return a.href?
a.innerHTML.link(a.href):(a.innerHTML||a.value).split(E)})).filter(function(a){return a})),x=u();(function(){d.innerHTML="";n=d.appendChild(document.createElement("div"));p=n.appendChild(document.createElement("div"));n.className="nsp_out";f=n.appendChild(document.createElement("input"));f.type="range";f.value=f.min=0;f.step=1;f.max=t.length;f.className="nsp_sli";f.disabled=!0;f.addEventListener("change",function(){h(f.value);p.innerHTML=t[f.value]});var a=n.appendChild(document.createElement("div"));
a.className="nsp_wdu";var b=a.appendChild(document.createElement("button"));b.className="nsp_wb";b.innerHTML="-";b.addEventListener("click",function(){return k(-10)});r=a.appendChild(document.createElement("input"));r.type="text";r.size="2";r.className="nsp_wad";r.value=l;r.addEventListener("blur",function(){return k(r.value-l)});b=a.appendChild(document.createElement("button"));b.className="nsp_wb";b.innerHTML="+";b.addEventListener("click",function(){return k(10)});a=n.appendChild(document.createElement("div"));
a.className="nsp_mcl";b=a.appendChild(document.createElement("button"));b.className="nsp_pb";b.innerHTML="&#9199;&#xFE0E;";b.addEventListener("click",function(){return g()});b=a.appendChild(document.createElement("button"));b.className="nsp_btn";b.innerHTML="&#9194;&#xFE0E;";b.addEventListener("click",function(){return e(-l/4)});w=n.appendChild(document.createElement("div"));w.className="nsp_tmr";w.innerHTML="0:00/"+m(x);b=a.appendChild(document.createElement("button"));b.className="nsp_btn";b.innerHTML=
"&#9193;&#xFE0E;";b.addEventListener("click",function(){return e(l/4)});b=a.appendChild(document.createElement("button"));b.className="nsp_btn";b.innerHTML="&times;&#xFE0E;";b.addEventListener("click",function(){d.innerHTML=""});p.className="nsp_inr";p.innerHTML="Press play";p.addEventListener("click",function(){return g()});n.onkeydown=function(q){switch(q.keyCode){case 32:g();break;case 27:d.innerHTML="";break;case 39:e(l/4);break;case 37:e(-l/4);break;case 38:k(10);break;case 40:k(-10)}};n.addEventListener("wheel",
function(q){e(q.wheelDelta/12)})})()};
